[package]
name = "migration-engine-cli"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
migration-connector = { path = "../connectors/migration-connector" }
migration-core = { path = "../core" }
user-facing-errors = { path = "../../libs/user-facing-errors" }

base64 = "0.13.0"
futures = "0.3.8"
json-rpc-stdio = { path = "../../libs/json-rpc-stdio" }
serde_json = { version = "1.0.59", features = ["float_roundtrip"] }
structopt = "0.3.20"
tokio = { version = "0.2.23", features = ["macros"] }
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tracing-error = "0.1.2"

[dev-dependencies]
tempfile = "3.1.0"
test-setup = { path = "../../libs/test-setup" }
url = "2.2.0"
quaint = { git = "https://github.com/prisma/quaint" }

[features]
default = ["sql"]
sql = ["migration-core/sql"]

[[bin]]
name = "migration-engine"
path = "src/main.rs"
