[workspace]
members = [
  "introspection-engine/connectors/introspection-connector",
  "introspection-engine/connectors/sql-introspection-connector",
  "introspection-engine/core",
  "introspection-engine/introspection-engine-tests",
  "libs/datamodel/connectors/datamodel-connector",
  "libs/datamodel/connectors/sql-datamodel-connector",
  "migration-engine/cli",
  "migration-engine/connectors/migration-connector",
  "migration-engine/connectors/sql-migration-connector",
  "migration-engine/core",
  "migration-engine/migration-engine-tests",
  "query-engine/connectors/query-connector",
  "query-engine/connectors/sql-query-connector",
  "query-engine/core",
  "query-engine/query-engine",
  "prisma-fmt",
  "libs/datamodel/core",
  "libs/feature-flags",
  "libs/json-rpc-stdio",
  "libs/native-types",
  "libs/prisma-inflector",
  "libs/prisma-models",
  "libs/prisma-value",
  "libs/sql-ddl",
  "libs/sql-schema-describer",
  "libs/test-cli",
  "libs/user-facing-errors",
]

[patch."https://github.com/prisma/quaint"]
quaint = { path = "../quaint" }

[profile.dev.package.backtrace]
opt-level = 3

[profile.release.package.introspection-core]
codegen-units = 1 
opt-level = 'z' # Optimize for size.
#strip="symbols"
