version: "3"
services:
  postgres9:
    image: postgres:9
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs9"
    ports:
      - "5431:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs9

  postgres10:
    image: postgres:10
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs10"
    ports:
      - "5432:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs10

  postgres11:
    image: postgres:11
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs11"
    ports:
      - "5433:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs11

  postgres12:
    image: postgres:12
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs12"
    ports:
      - "5434:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs12

  mysql-5-7:
    image: mysql:5.7
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
    networks:
      - databases
    tmpfs: /var/lib/mysql

  mysql-8-0:
    image: mysql:8.0
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3307:3306"
    networks:
      - databases
    tmpfs: /var/lib/mysql8

  mariadb-10-0:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3308:3306"
    networks:
      - databases
    tmpfs: /var/lib/mariadb

networks:
  databases:
