version: "3"
services:
  pgbouncer:
    image: brainsam/pgbouncer:latest
    restart: always
    environment:
      DB_HOST: "postgres11"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "prisma"
      POOL_MODE: "transaction"
      MAX_CLIENT_CONN: "1000"
    networks:
      - databases
    ports:
      - "6432:6432"

  postgres9:
    image: postgres:9
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs9"
    ports:
      - "5431:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs9

  postgres10:
    image: postgres:10
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs10"
    ports:
      - "5432:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs10

  postgres11:
    image: postgres:11
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs11"
    ports:
      - "5433:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs11

  postgres12:
    image: postgres:12
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs12"
    ports:
      - "5434:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs12

  postgres13:
    image: postgres:13
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs13"
    ports:
      - "5435:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs12

  mysql-5-6:
    image: mysql:5.6.50
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3309:3306"
    networks:
      - databases
    tmpfs: /var/lib/mysql

  mysql-5-7:
    image: mysql:5.7.32
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
    networks:
      - databases
    tmpfs: /var/lib/mysql

  mysql-8-0:
    image: mysql:8.0.22
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3307:3306"
    networks:
      - databases
    tmpfs: /var/lib/mysql8

  mariadb-10-0:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3308:3306"
    networks:
      - databases
    tmpfs: /var/lib/mariadb

  mssql-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
    networks:
      - databases

  mssql-2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1434:1433"
    networks:
      - databases

  mongo4:
    image: mongo:4.4.3-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "prisma"
      MONGO_INITDB_ROOT_PASSWORD: "prisma"
    ports:
      - "27017:27017"
    networks:
      - databases

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686" # the trace viewer (http)
    networks:
      - telemetry

  otel-agent:
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    restart: always
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger
    networks:
      - telemetry


  vttestserver57:
    image: vitess/vttestserver:mysql57
    restart: always
    ports:
      - 33577:33577
    environment:
      PORT: 33574
      KEYSPACES: a_default_can_be_dropped,a_model_can_be_removed,a_relation_with_mappings_on_both_sides_can_reference_multip,a_table_recreation_with_noncastable_columns_should_trigger_,adding_a_many_to_many_relation_must_result_in_a_prisma_styl,adding_a_many_to_many_relation_with_custom_name_must_work,adding_a_model_for_an_existing_table_must_work,adding_a_new_unique_field_must_work,adding_a_required_field_to_an_existing_table_with_data_with,adding_a_required_field_with_a_default_to_an_existing_table,adding_a_required_field_with_prisma_level_default_works,adding_a_required_field_without_default_to_an_existing_tabl,adding_a_scalar_field_must_work,adding_a_scalar_list_for_a_model_with_id_type_int_must_work,adding_a_unique_constraint_should_warn,adding_a_unique_constraint_when_existing_data_respects_it_w,adding_an_enum_field_must_work,adding_an_enum_field_must_work_with_native_types_off,adding_an_id_field_of_type_int_must_work,adding_an_id_field_of_type_int_must_work_for_sqlite,adding_an_id_field_of_type_int_with_autoincrement_works,adding_an_id_field_with_a_special_name_must_work,adding_an_inline_relation_must_result_in_a_foreign_key_in_t,adding_an_inline_relation_to_a_model_with_an_exotic_id_type,adding_an_optional_field_must_work,adding_an_unsupported_type_must_work,adding_and_removing_properties_on_unsupported_should_work,adding_multiple_optional_fields_to_an_existing_model_works,adding_mutual_references_on_existing_tables_works,adding_new_fields_with_multi_column_unique_must_work,adding_unique_to_an_existing_field_must_work,advisory_locking_works,altering_a_column_with_non_null_values_should_warn,altering_a_column_without_non_null_values_should_not_warn,altering_the_type_of_a_column_in_a_non_empty_table_warns,altering_the_type_of_a_column_in_an_empty_table_should_not_,an_enum_can_be_turned_into_a_model,apply_migrations_with_an_empty_migrations_folder_works,applying_a_single_migration_should_work,applying_two_migrations_works,arity_is_preserved_by_alter_enum,arity_of_enum_columns_can_be_changed,authentication_failure_must_return_a_known_error_on_mysql,authentication_failure_must_return_a_known_error_on_postgre,bad_datasource_url_and_provider_combinations_must_return_a_,bad_migrations_should_make_the_command_fail_with_a_good_err,baselining_should_work,basic_compound_primary_keys_must_work,basic_create_migration_works,bigint_primary_keys_are_idempotent,bytes_columns_are_idempotent,bytes_to_bytes_array_works,bytes_to_string_works,can_handle_reserved_sql_keywords_for_field_name,can_handle_reserved_sql_keywords_for_model_name,changing_a_column_from_optional_to_required_is_unexecutable,changing_a_column_from_optional_to_required_with_a_default_,changing_a_column_from_required_to_optional_should_work,changing_a_relation_field_to_a_scalar_field_must_work,changing_a_scalar_field_to_a_relation_field_must_work,changing_a_string_array_column_to_scalar_is_fine,changing_all_referenced_columns_of_foreign_key_works,changing_an_int_array_column_to_scalar_is_not_possible,changing_the_type_of_a_field_referenced_by_a_fk_must_work,changing_the_type_of_an_id_field_must_work,column_defaults_can_safely_be_changed,column_defaults_must_be_migrated,compound_foreign_keys_should_work_in_correct_order,compound_primary_keys_on_mapped_columns_must_work,connecting_to_a_postgres_database_with_missing_schema_creat,connection_string_problems_give_a_nice_error,connections_to_system_databases_must_be_rejected,create_enum_renders_correctly,create_enum_step_only_rendered_when_needed,created_at_does_not_get_arbitrarily_migrated,creating_a_field_for_an_existing_column_and_changing_its_ty,creating_a_field_for_an_existing_column_and_simultaneously_,creating_a_field_for_an_existing_column_with_a_compatible_t,creating_a_migration_with_a_non_existent_migrations_directo,creating_a_model_with_a_non_autoincrement_id_column_is_idem,creating_a_scalar_list_field_for_an_existing_table_must_wor,creating_a_second_migration_should_have_the_previous_sql_sc,creating_tables_without_primary_key_must_work,database_access_denied_must_return_a_proper_error_in_rpc,database_does_not_exist_must_return_a_proper_error,database_level_json_defaults_can_be_defined,datamodel_parser_errors_must_return_a_known_error,datetime_defaults_work,datetime_to_float_conversions_are_impossible,decimal_columns_are_idempotent,decimal_to_decimal_array_works,decimal_to_float_works,default_current_timestamp_precision_follows_column_precisio,delete_a_field_for_a_non_existent_column_must_work,deleting_a_scalar_list_field_for_a_non_existent_column_must,dev_diagnostic_after_two_migrations_happy_path,dev_diagnostic_calculates_drift_in_presence_of_failed_migra,dev_diagnostic_can_detect_edited_migrations,dev_diagnostic_can_detect_when_history_diverges,dev_diagnostic_can_detect_when_the_migrations_directory_is_,dev_diagnostic_detects_drift,dev_diagnostic_on_an_empty_database_without_migration_retur,dev_diagnostic_reports_migrations_failing_to_apply_cleanly,dev_diagnostic_returns_create_migration_when_the_database_i,dev_diagnostic_shadow_database_creation_error_is_special_ca,dev_diagnostic_with_a_nonexistent_migrations_directory_work,diagnose_migration_history_calculates_drift_in_presence_of_,diagnose_migration_history_with_opt_in_to_shadow_database_c,diagnose_migration_history_without_opt_in_to_shadow_databas,diagnose_migrations_history_after_two_migrations_happy_path,diagnose_migrations_history_can_detect_edited_migrations,diagnose_migrations_history_can_detect_when_history_diverge,diagnose_migrations_history_can_detect_when_the_database_is,diagnose_migrations_history_can_detect_when_the_folder_is_b,diagnose_migrations_history_on_an_empty_database_without_mi,diagnose_migrations_history_reports_migrations_failing_to_a,diagnose_migrations_history_with_a_nonexistent_migrations_d,drift_can_be_detected_without_migrations_table,dropping_a_column_with_non_null_values_should_warn,dropping_a_model_with_a_multi_field_unique_index_must_work,dropping_a_table_referenced_by_foreign_keys_must_work,dropping_a_table_with_rows_should_warn,dropping_enum_values_should_warn,dropping_mutually_referencing_tables_works,empty_migration_directories_should_cause_known_errors,empty_migrations_should_be_created_with_the_draft_option,empty_migrations_should_not_be_created,enum_creation_is_idempotent,enum_defaults_must_work,enum_field_to_string_field_works,enum_value_with_database_names_must_work,enum_variants_can_be_added_without_data_loss,enum_variants_can_be_dropped_without_data_loss,enums_can_be_dropped_on_postgres,enums_used_in_default_can_be_changed,enums_work_when_table_name_is_remapped,escaped_string_defaults_are_not_arbitrarily_migrated,evaluate_data_loss_maps_warnings_to_the_right_steps,evaluate_data_loss_returns_warnings_for_the_local_database_,evaluate_data_loss_with_an_up_to_date_database_returns_no_s,evaluate_data_loss_with_not_up_to_date_db_and_pending_chang,evaluate_data_loss_with_past_unapplied_migrations_with_dest,evaluate_data_loss_with_up_to_date_db_and_pending_changes_r,existing_enums_are_picked_up,existing_postgis_tables_must_not_be_migrated,failing_enum_migrations_should_not_be_partially_applied,finishing_a_migration_works,flipping_autoincrement_on_and_off_works,float_columns_are_idempotent,float_to_decimal_works,foreign_keys_are_added_on_existing_tables,foreign_keys_can_be_added_on_existing_columns,foreign_keys_can_be_dropped_on_existing_columns,foreign_keys_of_inline_one_to_one_relations_have_a_unique_c,foreign_keys_to_indexes_being_renamed_must_work,function_expressions_as_dbgenerated_work,id_as_part_of_relation_must_work,impossible_casts_with_existing_data_should_warn,index_on_compound_relation_fields_must_work,index_renaming_must_work,index_renaming_must_work_when_renaming_to_custom,index_renaming_must_work_when_renaming_to_default,index_settings_must_be_migrated,index_updates_with_rename_must_work,indexes_and_unique_constraints_on_the_same_field_do_not_col,indexes_on_composite_relation_fields,indexes_on_foreign_key_fields_are_not_created_twice,indexes_with_an_automatically_truncated_name_are_idempotent,int_to_string_conversions_work,join_tables_between_models_with_compound_primary_keys_must_,join_tables_between_models_with_mapped_compound_primary_key,json_fields_can_be_created,json_fields_must_be_rejected,list_migration_directories_with_an_empty_migrations_folder_,listing_a_single_migration_name_should_work,making_a_column_required_in_an_empty_table_should_not_warn,making_an_autoincrement_default_an_expression_then_autoincr,making_an_existing_id_field_autoincrement_works,making_an_existing_id_field_autoincrement_works_with_foreig,making_an_existing_id_field_autoincrement_works_with_indice,making_an_optional_field_required_on_an_empty_table_works,making_an_optional_field_required_with_data_with_a_default_,making_an_optional_field_required_with_data_without_a_defau,mark_migration_applied_on_a_non_empty_database_works,mark_migration_applied_on_an_empty_database_works,mark_migration_applied_when_the_migration_is_already_applie,mark_migration_applied_when_the_migration_is_failed,mark_migration_rolled_back_on_a_database_with_migrations_ta,mark_migration_rolled_back_on_an_empty_database_errors,mark_migration_rolled_back_with_a_failed_migration_works,mark_migration_rolled_back_with_a_successful_migration_erro,migrating_a_required_column_from_int_to_string_should_cast,migrating_a_unique_constraint_to_a_primary_key_works,migration_name_length_is_validated,migrations_should_fail_on_an_uninitialized_nonempty_databas,migrations_should_fail_when_the_script_is_invalid,migrations_should_not_reapply_modified_migrations,migrations_should_succeed_on_an_uninitialized_nonempty_data,migrations_with_many_to_many_related_models_must_not_recrea,model_with_multiple_indexes_works,models_with_an_autoincrement_field_as_part_of_a_multi_field,models_with_enum_values_can_be_dropped,moving_an_inline_relation_to_the_other_side_must_work,multi_column_indexes_and_unique_constraints_on_the_same_fie,multi_column_unique_in_conjunction_with_custom_column_name_,multi_field_id_as_part_of_relation_must_work,multiple_successive_migrations_work,must_return_helpful_error_on_migration_not_found,native_type_columns_can_be_created,new_index_with_same_name_as_index_from_dropped_table_works,no_additional_unique_created,not_castable_with_existing_data_should_warn,one_to_many_self_relations_do_not_create_a_unique_index,primary_key_migrations_do_not_cause_data_loss,references_to_models_with_compound_primary_keys_must_work,relations_can_reference_arbitrary_unique_fields,relations_can_reference_arbitrary_unique_fields_with_maps,relations_can_reference_multiple_fields,relations_to_models_with_no_pk_and_a_single_unique_required,relations_to_models_without_a_primary_key_work,relations_with_mappings_on_referenced_side_can_reference_mu,relations_with_mappings_on_referencing_side_can_reference_m,remapped_multi_field_id_as_part_of_relation_must_work,removing_a_model_for_a_table_that_is_already_deleted_must_w,removing_a_relation_field_must_work,removing_a_scalar_field_must_work,removing_an_existing_unique_field_must_work,removing_an_inline_relation_must_work,removing_autoincrement_from_an_existing_field_works,removing_multi_field_unique_index_must_work,removing_unique_from_an_existing_field_must_work,renaming_a_datasource_works,renaming_a_field_where_the_column_was_already_renamed_must_,reordering_and_altering_models_at_the_same_time_works,reserved_sql_key_words_must_work,reset_then_apply_with_migrations_directory_works,reset_then_diagnostics_with_migrations_directory_works,reset_works,risky_casts_with_existing_data_should_warn,rolling_back_applying_again_then_rolling_back_again_should_,safe_casts_from_array_with_existing_data_should_work,safe_casts_with_existing_data_should_work,schema_push_happy_path,schema_push_warns_about_destructive_changes,schema_push_with_an_unexecutable_migration_returns_a_messag,schemas_with_dbgenerated_expressions_work,schemas_with_dbgenerated_work,set_default_current_timestamp_on_existing_column_works,shadow_database_creation_error_is_special_cased_mssql,shadow_database_creation_error_is_special_cased_mysql,shadow_database_creation_error_is_special_cased_postgres,shadow_db_url_can_be_configured_on_postgres,shared_default_constraints_are_ignored_issue_5423,simple_type_aliases_in_migrations_must_work,soft_resets_work_on_mysql,soft_resets_work_on_postgres,soft_resets_work_on_sql_server,specifying_a_db_name_for_an_inline_relation_must_work,sqlite_must_recreate_indexes,sqlite_must_recreate_multi_field_indexes,squashing_migrations_history_at_the_end_works,squashing_migrations_history_at_the_start_works,squashing_whole_migration_history_works,starting_a_migration_works,string_columns_do_not_get_arbitrarily_migrated,string_field_to_enum_field_works,string_to_bytes_works,string_to_int_conversions_are_risky,switching_an_unsupported_type_to_supported_must_work,switching_databases_must_work,typescript_starter_schema_is_idempotent_without_native_type,typescript_starter_schema_starting_without_native_types_is_,typescript_starter_schema_with_different_native_types_is_id,typescript_starter_schema_with_differnt_native_types_is_ide,typescript_starter_schema_with_native_types_is_idempotent,unique_constraint_errors_in_migrations_must_return_a_known_,unique_constraints_on_composite_relation_fields,unique_directive_on_required_one_to_one_relation_creates_on,unique_in_conjunction_with_custom_column_name_must_work,unreachable_database_must_return_a_proper_error_on_mysql,unreachable_database_must_return_a_proper_error_on_postgres,unsupported_type_renders_correctly,update_type_of_scalar_field_must_work,updating_a_field_for_a_non_existent_column,updating_db_name_of_a_scalar_field_must_work,updating_then_finishing_a_migration_works,using_unsupported_and_ignore_should_work,uuids_do_not_generate_drift_issue_5282,variants_can_be_added_to_an_existing_enum,variants_can_be_removed_from_an_existing_enum,with_a_failed_migration,with_an_invalid_unapplied_migration_should_report_it
      NUM_SHARDS: 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
      MYSQL_BIND_HOST: "0.0.0.0"
    networks:
      - databases
      
  vttestserver80:
    image: vitess/vttestserver:mysql80
    restart: always
    ports:
      - 33807:33807
    environment:
      PORT: 33804
      KEYSPACES: test
      NUM_SHARDS: "1"
      MYSQL_BIND_HOST: "0.0.0.0"
    networks:
      - databases

networks:
  databases:
  telemetry:
