networks:
  test:

services:
  consul1:
    command: agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0
    hostname: consul1
    image: consul:latest
    networks:
    - test
  consul2:
    command: agent -server -retry-join consul1 -disable-host-node-id
    depends_on:
    - consul1
    expose:
    - "8400"
    - "8500"
    - "8600"
    hostname: consul2
    image: consul:latest
    networks:
    - test
  consul3:
    command: agent -server -retry-join consul1 -disable-host-node-id
    depends_on:
    - consul1
    expose:
    - "8400"
    - "8500"
    - "8600"
    hostname: consul3
    image: consul:latest
    networks:
    - test
  external_db_host:
    build:
      context: ./external_db/mysql
      dockerfile: Dockerfile
    command:
    - --server-id=1
    - --log-bin=mysql-bin
    - --gtid_mode=ON
    - --enforce_gtid_consistency
    - --general_log=1
    - --slow_query_log=1
    environment:
      MYSQL_DATABASE: ${DB:-test}
      MYSQL_PASSWORD: ${DB_PASS:-external_db_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
      MYSQL_USER: ${DB_USER:-external_db_user}
    healthcheck:
      retries: 10
      test: /usr/bin/mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} --execute
        "SHOW DATABASES;"
      timeout: 10s
    ports:
    - "3306"
    restart: always
    volumes:
    - ./external_db/mysql/:/docker-entrypoint-initdb.d/
    - ./external_db/mysql/log:/var/log/mysql
    networks:
    - test
  vtctld:
    command:
    - sh
    - -c
    - ' /vt/bin/vtctld -topo_implementation consul -topo_global_server_address consul1:8500
      -topo_global_root vitess/global -cell test -workflow_manager_init -workflow_manager_use_election
      -service_map ''grpc-vtctl'' -backup_storage_implementation file -file_backup_storage_root
      /vt/vtdataroot/backups -logtostderr=true -port 8080 -grpc_port 15999 '
    depends_on:
      external_db_host:
        condition: service_healthy
    image: vitess/lite:mysql80
    ports:
    - 15000:8080
    - "15999"
    volumes:
    - .:/script
    networks:
    - test
  vtgate:
    command:
    - sh
    - -c
    - '/script/run-forever.sh /vt/bin/vtgate -topo_implementation consul -topo_global_server_address
      consul1:8500 -topo_global_root vitess/global -logtostderr=true -port 8080 -grpc_port
      15999 -mysql_server_port 15306 -mysql_auth_server_impl none -cell test -cells_to_watch
      test -tablet_types_to_wait MASTER,REPLICA,RDONLY -service_map ''grpc-vtgateservice''
      -normalize_queries=true -mysql_server_version ''8.0.22'''
    depends_on:
    - vtctld
    image: vitess/lite:mysql80
    ports:
    - 15099:8080
    - "15999"
    - 15306:15306
    volumes:
    - .:/script
    networks:
    - test
  vtorc:
    command:
    - sh
    - -c
    - /script/vtorc-up.sh
    depends_on:
    - vtctld
    environment:
    - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
      -topo_global_root vitess/global
    - EXTERNAL_DB=0
    - DB_USER=
    - DB_PASS=
    image: vitess/lite:mysql80
    ports:
    - 13000:3000
    volumes:
    - .:/script
    networks:
    - test
  vttablet101:
    command:
    - sh
    - -c
    - /script/vttablet-up.sh 101
    depends_on:
    - vtctld
    environment:
    - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
      -topo_global_root vitess/global
    - WEB_PORT=8080
    - GRPC_PORT=15999
    - CELL=test
    - KEYSPACE=test
    - SHARD=-
    - ROLE=master
    - VTHOST=vttablet101
    - EXTERNAL_DB=0
    - DB_PORT=
    - DB_HOST=
    - DB_USER=
    - DB_PASS=
    - DB_CHARSET=
    healthcheck:
      interval: 30s
      retries: 15
      test:
      - CMD-SHELL
      - curl -s --fail --show-error localhost:8080/debug/health
      timeout: 10s
    image: vitess/lite:mysql80
    ports:
    - 15101:8080
    - "15999"
    - "3306"
    volumes:
    - .:/script
    networks:
    - test
  shadowdb:
    image: mysql:8.0.22
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3309:3306"
    networks:
      - test
    tmpfs: /var/lib/mysql8

version: "2.1"
