[package]
authors = [""]
edition = "2018"
name = "mongodb-migration-connector"
version = "0.1.0"

[dependencies]
datamodel = { path = "../../../libs/datamodel/core" }
datamodel-connector = { path = "../../../libs/datamodel/connectors/datamodel-connector" }
migration-connector = { path = "../migration-connector" }
native-types = { path = "../../../libs/native-types" }
prisma-value = { path = "../../../libs/prisma-value" }
user-facing-errors = { path = "../../../libs/user-facing-errors", features = ["sql"] }

anyhow = "1.0.26"
async-trait = "0.1.17"
chrono = { version = "0.4" }
connection-string = "0.1.10"
enumflags2 = "0.6.0"
indoc = "1.0"
mongodb = { git = "https://github.com/mongodb/mongo-rust-driver.git" }
once_cell = "1.3"
regex = "1"
serde_json = { version = "1.0" }
tokio = { version = "1.0", default-features = false, features = ["time"] }
tracing = "0.1.10"
tracing-futures = "0.2.0"
url = "2.1.1"
uuid = { version = "0.8", features = ["v4"] }
