[package]
name = "sql-query-connector"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
itertools = "0.8"
serde_json = "1.0"
uuid = "0.8"
failure = "0.1"
url = "2"
rand = "0.7"
log = "0.4"
async-trait = "0.1"
futures = "0.3"
rust_decimal = "=1.1.0"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = ["full", "tracing-log"]

[dependencies.connector-interface]
path = "../query-connector"
package = "query-connector"

[dependencies.prisma-models]
path = "../../../libs/prisma-models"
features = ["sql-ext"]

[dependencies.prisma-value]
path = "../../../libs/prisma-value"
features = ["sql-ext"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.datamodel]
path = "../../../libs/datamodel/core"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.cuid]
git = "https://github.com/prisma/cuid-rust"

[dependencies.user-facing-errors]
path = "../../../libs/user-facing-errors"
features = ["sql"]
