[package]
authors = []
edition = "2018"
name = "sql-query-connector"
version = "0.1.0"

[dependencies]
anyhow = "1.0.34"
async-trait = "0.1.42"
futures = "0.3.8"
itertools = "0.8.2"
rand = "0.7.3"
bigdecimal = "0.2.0"
serde_json = { version = "1.0.59", features = ["float_roundtrip"] }
thiserror = "1.0.22"
tokio = "0.2.23"
uuid = "0.8.1"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = [
    "pooled",
    "json",
    "uuid",
    "chrono",
    "sqlite",
    "postgresql",
    "mysql",
    "mssql",
    "tracing-log",
    "bigdecimal"
]

[dependencies.connector-interface]
package = "query-connector"
path = "../query-connector"

[dependencies.prisma-models]
features = ["sql-ext"]
path = "../../../libs/prisma-models"

[dependencies.prisma-value]
features = ["sql-ext"]
path = "../../../libs/prisma-value"

[dependencies.chrono]
features = ["serde"]
version = "0.4.19"

[dependencies.datamodel]
path = "../../../libs/datamodel/core"

[dependencies.serde]
features = ["derive"]
version = "1.0.117"

[dependencies.cuid]
git = "https://github.com/prisma/cuid-rust"

[dependencies.user-facing-errors]
features = ["sql"]
path = "../../../libs/user-facing-errors"
