[package]
authors = ["Dominic Petrick <dompetrick@gmail.com>", "Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
name = "query-core"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
base64 = "0.12"
bigdecimal = "0.2"
chrono = "0.4"
connector = {path = "../connectors/query-connector", package = "query-connector"}
crossbeam-queue = "0.2"
datamodel-connector = {path = "../../libs/datamodel/connectors/datamodel-connector"}
feature-flags = {path = "../../libs/feature-flags"}
futures = "0.3"
im = "13.0"
indexmap = {version = "1.0", features = ["serde-1"]}
itertools = "0.8"
once_cell = "1.3"
petgraph = "0.4"
prisma-inflector = {path = "../../libs/prisma-inflector"}
prisma-models = {path = "../../libs/prisma-models"}
prisma-value = {path = "../../libs/prisma-value"}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1.0"
tracing = {version = "0.1", features = ["attributes"]}
tracing-futures = "0.2.4"
tokio = {version = "1.0"}
user-facing-errors = {path = "../../libs/user-facing-errors"}
uuid = "0.8"
