[package]
name = "query-core"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>", "Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
prisma-models = { path = "../../libs/prisma-models" }
prisma-inflector = { path = "../../libs/prisma-inflector" }
connector = { path = "../connectors/query-connector", package = "query-connector" }
failure = { version =  "0.1", features = ["derive"] }
lazy_static = "1.4"
uuid = "0.8"
indexmap = "1.0"
itertools = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
once_cell = "1.2"
debug_stub_derive = "0.3"
log = "0.4"
petgraph = "0.4"
im = "13.0"
futures = "0.3"
async-std = { version = "0.99", features = ["unstable"] }
async-trait = "0.1"
crossbeam-queue = "0.2"
rust_decimal = "1.2"
user-facing-errors = { path = "../../libs/user-facing-errors" }
