[package]
authors = ["Dominic Petrick <dompetrick@gmail.com>", "Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
name = "query-core"
version = "0.1.0"

[dependencies]
async-trait = "0.1.42"
chrono = "0.4.19"
connector = {path = "../connectors/query-connector", package = "query-connector"}
crossbeam-queue = "0.2.3"
feature-flags = {path = "../../libs/feature-flags"}
futures = "0.3.8"
im = "13.0.0"
indexmap = { version = "1.6.0", features = ["serde-1"] }
itertools = "0.8.2"
once_cell = "1.5.2"
petgraph = "0.4.13"
bigdecimal = "0.2.0"
prisma-inflector = {path = "../../libs/prisma-inflector"}
prisma-models = {path = "../../libs/prisma-models"}
datamodel-connector = {path = "../../libs/datamodel/connectors/datamodel-connector"}
prisma-value = {path = "../../libs/prisma-value"}
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
thiserror = "1.0.22"
tokio = "0.2.23"
tracing = "0.1.22"
user-facing-errors = {path = "../../libs/user-facing-errors"}
uuid = "0.8.1"
base64 = "0.12.3"
