[package]
name = "introspection-connector"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
datamodel = { path = "../../../libs/datamodel/core" }
thiserror = "1.0.22"
anyhow = "1.0.34"

serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.59", features = ["float_roundtrip"] }
user-facing-errors = { path = "../../../libs/user-facing-errors" }
