[package]
name = "sql-introspection-connector"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.17"
introspection-connector = { path = "../introspection-connector" }
sql-schema-describer = { path = "../../../libs/sql-schema-describer" }
prisma-inflector = { path = "../../../libs/prisma-inflector" }
datamodel = { path = "../../../libs/datamodel/core" }
serde_json = "1.0"
failure = "0.1"
log = "0.4"
regex = "1.2"
url = "1.7"
user-facing-errors = { path = "../../../libs/user-facing-errors", features = ["sql"] }
tracing = "0.1.10"
tracing-futures = "0.2.0"
tokio = { version = "0.2", features = ["rt-threaded", "time"] }

[dependencies.quaint]
version = "0.2.0-alpha.1"
features = ["single"]

[dev-dependencies]
barrel = { version = "0.6.5-alpha.0", features = ["sqlite3", "mysql", "pg"] }
test-macros = { path = "../../../libs/test-macros" }
test-setup = { path = "../../../libs/test-setup" }
once_cell = "1.2.0"
pretty_assertions = "0.6.1"
