[package]
name = "sql-introspection-connector"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "=1.1.0"
prisma-value = { path = "../../../libs/prisma-value" }
async-trait = "0.1.17"
introspection-connector = { path = "../introspection-connector" }
sql-schema-describer = { path = "../../../libs/sql-schema-describer" }
datamodel = { path = "../../../libs/datamodel/core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.9"
anyhow = "1.0.26"
regex = "1.2"
user-facing-errors = { path = "../../../libs/user-facing-errors", features = ["sql"] }
tracing = "0.1.10"
tracing-futures = "0.2.0"
tokio = { version = "=0.2.13", features = ["rt-threaded", "time"] }
once_cell = "1.3"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = ["single"]

[dev-dependencies]
barrel = { version = "0.6.5-alpha.0", features = ["sqlite3", "mysql", "pg"] }
test-macros = { path = "../../../libs/test-macros" }
test-setup = { path = "../../../libs/test-setup" }
pretty_assertions = "0.6.1"
