[package]
name = "query-engine-napi"
version = "0.1.0"
authors = ["Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
vendored-openssl = ["sql-connector/vendored-openssl"]

[dependencies]
query-core = { path = "../core" }
request-handlers = { path = "../request-handlers" }
query-connector = { path = "../connectors/query-connector" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
datamodel = { path = "../../libs/datamodel/core" }
feature-flags = {path = "../../libs/feature-flags"}
sql-connector = {path = "../connectors/sql-query-connector", package = "sql-query-connector"}
prisma-models = { path = "../../libs/prisma-models" }
napi = { version = "1", default-features = false, features = ["napi4", "tokio_rt", "serde-json"] }
napi-derive = "1"
thiserror = "1"
connection-string = "0.1"
url = "2"
serde_json = "1"
serde = "1"
tracing = "0.1"
tracing-attributes = "0.1"
tracing-subscriber = { version = "0.2", features = ["json"] }
tracing-futures = "0.2.3"
tokio = { version = "1", features = ["sync"] }

[build-dependencies]
napi-build = "1"
