[package]
name = "migration-core"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>", "Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[dependencies]
datamodel = { path = "../../libs/datamodel/core" }
migration-connector = { path = "../connectors/migration-connector" }
sql-migration-connector = { path = "../connectors/sql-migration-connector", optional = true }
user-facing-errors = { path = "../../libs/user-facing-errors" }

anyhow = "1.0.34"
async-trait = "0.1.42"
chrono = { version = "0.4.19", features = ["serde"] }
futures = { version = "0.3.8", default-features = false, features = ["compat"] }
jsonrpc-core = "14.2.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.59", features = ["float_roundtrip"] }
tracing = "0.1.22"
tracing-futures = "0.2.4"
url = "2.2.0"

[features]
default = ["sql"]
sql = ["sql-migration-connector"]
