[package]
name = "query-connector"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
anyhow = "1.0.34"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.59", features = ["float_roundtrip"] }
once_cell = "1.5.2"
prisma-models = { path = "../../../libs/prisma-models" }
prisma-value = { path = "../../../libs/prisma-value" }
thiserror = "1.0.22"
uuid = "0.8.1"
itertools = "0.8.2"
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.8"
user-facing-errors = { path = "../../../libs/user-facing-errors" }
async-trait = "0.1.42"
