[package]
name = "introspection-engine-tests"
version = "0.1.0"
authors = ["Julius de Bruijn <julius+github@nauk.io>"]
edition = "2018"

[dependencies]
sql-datamodel-connector = { path = "../../libs/datamodel/connectors/sql-datamodel-connector" }
sql-introspection-connector = { path = "../connectors/sql-introspection-connector" }
introspection-connector = { path = "../connectors/introspection-connector" }
introspection-core = { path = "../core" }
datamodel-connector = { path = "../../libs/datamodel/connectors/datamodel-connector" }
sql-schema-describer = { path = "../../libs/sql-schema-describer" }
datamodel = { path = "../../libs/datamodel/core" }
test-macros = { path = "../../libs/test-macros" }
test-setup = { path = "../../libs/test-setup" }
enumflags2 = "0.6.4"

serde = { version = "1.0.117", features = ["derive"] }
pretty_assertions = "0.6.1"
tracing-futures = "0.2.4"
serde_json = { version = "1.0.59", features = ["float_roundtrip"] }
tracing = "0.1.22"
eyre = "0.6.3"
indoc = "1.0.3"

[dependencies.barrel]
git = "https://github.com/prisma/barrel.git"
features = ["sqlite3", "mysql", "pg", "mssql"]
branch = "mssql-support"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = [
    "postgresql",
    "mysql",
    "mssql",
    "sqlite",
    "json",
    "uuid",
    "chrono",
    "bigdecimal"
]
