[package]
authors = ["Dominic Petrick <dompetrick@gmail.com>", "Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
name = "query-engine"
version = "0.1.0"

[features]
default = ["sql", "graphql"]
graphql = ["graphql-parser"]
sql = ["sql-connector"]

[dependencies]
futures = "0.3.8"
tokio = { version = "0.2.23", features = ["rt-threaded", "macros"] }

anyhow = "1.0.34"
async-std = { version = "1.7.0", features = ["attributes", "tokio02"] }
async-trait = "0.1.42"
base64 = "0.12.3"
connector = {path = "../connectors/query-connector", package = "query-connector"}
connection-string = "0.1.10"
datamodel = {path = "../../libs/datamodel/core"}
datamodel-connector = {path = "../../libs/datamodel/connectors/datamodel-connector"}
feature-flags = {path = "../../libs/feature-flags"}
graphql-parser = {git = "https://github.com/prisma/graphql-parser", optional = true}
indexmap = { version = "1.6.0", features = ["serde-1"] }
itertools = "0.8.2"
once_cell = "1.5.2"
prisma-models = {path = "../../libs/prisma-models"}
query-core = {path = "../core"}
bigdecimal = "0.2.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.59", features = ["preserve_order", "float_roundtrip"] }
sql-connector = {path = "../connectors/sql-query-connector", optional = true, package = "sql-query-connector"}
structopt = "0.3.20"
thiserror = "1.0.22"
tide = { version = "0.15.0", default-features = false, features = ["h1-server", "logger"] }
tide-server-timing = "0.15.0"
url = "2.2.0"

tracing = "0.1.22"
tracing-attributes = "0.1.11"
tracing-subscriber = { version = "0.2.15", features = ["json"] }

tracing-futures = "0.2.4"
user-facing-errors = {path = "../../libs/user-facing-errors"}

[build-dependencies]
rustc_version = "0.2.3"

[dev-dependencies]
anyhow = "1.0.34"
chrono = "0.4.19"
indoc = "0.3.6"
migration-connector = {path = "../../migration-engine/connectors/migration-connector"}
migration-core = {path = "../../migration-engine/core"}
serial_test = "0.5.0"
sql-migration-connector = {path = "../../migration-engine/connectors/sql-migration-connector"}
test-macros = {path = "../../libs/test-macros"}
test-setup = {path = "../../libs/test-setup"}

[dev-dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = [
    "pooled",
    "json",
    "uuid",
    "chrono",
    "sqlite",
    "postgresql",
    "mysql",
    "mssql",
    "tracing-log",
    "bigdecimal"
]
