[package]
name = "introspection-core"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

# Please keep the pyramid form
[dependencies]
clap = "2.33"
serde = "1.0"
futures = { version = "0.3", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
failure = "0.1"

serde_json = "1.0"
serde_derive = "1.0"
async-trait = "0.1.17"
jsonrpc-core = "14.0"
jsonrpc-derive = "14.0"
jsonrpc-core-client = "14.0"
json-rpc-stdio = { path = "../../libs/json-rpc-stdio" }

datamodel = { path = "../../libs/datamodel/core" }
user-facing-errors = { path = "../../libs/user-facing-errors" }
introspection-connector = { path = "../connectors/introspection-connector" }
sql-introspection-connector = { path = "../connectors/sql-introspection-connector" }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[dependencies.tokio]
version = "0.2"
features = ["macros"]

[dev-dependencies]
pretty_assertions = "0.6.1"
test-setup = { path = "../../libs/test-setup" }
url = "2.1.0"



[[bin]]
name = "introspection-engine"
path = "src/main.rs"

