on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit on the given branch to build"
        required: true

jobs:
  build:
    name: "Windows engines build on branch ${{ github.event.ref }} for commit ${{ github.event.inputs.commit }}"
    env:
      SQLITE_MAX_VARIABLE_NUMBER: 250000
      SQLITE_MAX_EXPR_DEPTH: 10000
    runs-on: windows-latest
    steps:
      - name: Output link to real commit
        run: echo ${{ github.repository }}/commit/${{ github.event.inputs.commit }}

      - name: Checkout ${{ github.event.inputs.commit }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            ${{ github.workspace }}/target/release/*.exe
            ${{ github.workspace }}/target/release/*.dll

  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        db:
          - mysql
          - mariadb
        rust:
          - stable
        os:
          - windows-latest

    runs-on: ${{ matrix.os }}

    name: "Windows Migration Engine ${{ matrix.db }} test run on branch ${{ github.event.ref }} for commit ${{ github.event.inputs.commit }}"

    env:
      MYSQL_8_TEST_URL: "mysql://root@localhost:3306?connect_timeout=20&socket_timeout=60"
      MARIADB_TEST_URL: "mysql://root@localhost:3306?connect_timeout=20&socket_timeout=60"

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ matrix.db }}

      - name: Install ${{ matrix.db }}
        run: choco install ${{ matrix.db }}

      - name: Run tests
        run: cargo test -p migration-engine-tests ${{ matrix.db == 'mysql' && 'mysql_8' || 'mariadb' }}
