name: Migration Engine
on:
  push:

jobs:

  test:
    name: "Test Migration Engine - vttestserver"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: docker-compose up -d vttestserver57
      
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
          
      - run: mysql -h 127.0.0.1 -P 33577 -u test -ptest -e "SHOW DATABASES;"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: migration-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: timeout 40m cargo test mysql_5_6
        working-directory: migration-engine/migration-engine-tests
        env:
          CLICOLOR_FORCE: 1

      - run: docker ps -a
        if: ${{ always() }}
      - run: docker logs prisma-engines_vttestserver57_1
        if: ${{ always() }}
