name: Migration Engine
on:
  push:

jobs:

  compile:
    name: "Compile Migration Engine tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: migration-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test --no-run
        working-directory: migration-engine/migration-engine-tests

  test:
    name: "Test Migration Engine - ${{ matrix.database }}"

    strategy:
      fail-fast: false
      matrix:
        database: [mssql_2017, mssql_2019, mysql_5_6, mysql, mysql_8, mysql_mariadb, postgres9, postgres10, postgres11, postgres12, postgres13, sqlite]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start databases"
        run: docker-compose up -d

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      # - uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cargo/registry
      #       ~/.cargo/git
      #       target
      #     key: migration-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: timeout 40m cargo test ${{ matrix.database }}
        working-directory: migration-engine/migration-engine-tests
        env:
          CLICOLOR_FORCE: 1
