name: Migration Engine
on:
  push:

jobs:


  test:
    name: "Test Migration Engine - vttestserver"

    services:
      vttestserver57:
        image: vitess/vttestserver:mysql57
        ports:
          - 33577:33577
        env:
          PORT: 33574
          KEYSPACES: test,a_model_can_be_removed,a_default_can_be_dropped
          NUM_SHARDS: 1,1,1
          MYSQL_BIND_HOST: "0.0.0.0"
        options: --health-cmd="mysqladmin ping -h127.0.0.1 -P33577" --health-interval=5s --health-timeout=2s --health-retries=5

    runs-on: ubuntu-latest
    steps:
    
      - run: mysql -h 127.0.0.1 -P 33577 -u test -ptest -e "SHOW DATABASES;"
      
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: migration-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: timeout 40m cargo test mysql_5_6
        working-directory: migration-engine/migration-engine-tests
        env:
          CLICOLOR_FORCE: 1
