name: Query Engine
on:
  push:

jobs:

  compile:
    name: "Compile Query Engine tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: query-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test --no-run
        working-directory: query-engine

  test:
    name: "Test Query Engine - ${{ matrix.segment }}"
    
    strategy:
      fail-fast: false
      matrix:
        segment: [""]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start databases"
        run: docker-compose up -d
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: query-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test ${{ matrix.segment }}
        working-directory: query-engine
